// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NationalParks.DataAccess;

namespace NationalParks.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191120235832_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NationalParks.Models.Park", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("description");

                    b.Property<string>("designation");

                    b.Property<string>("directionsInfo");

                    b.Property<string>("directionsUrl");

                    b.Property<string>("fullName");

                    b.Property<string>("latLong");

                    b.Property<string>("name");

                    b.Property<string>("parkCode");

                    b.Property<string>("states");

                    b.Property<string>("url");

                    b.Property<string>("weatherInfo");

                    b.HasKey("id");

                    b.ToTable("Parks");
                });
#pragma warning restore 612, 618
        }
    }
}
